#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpwquality
Version  : 1.4.0
Release  : 24
URL      : https://github.com/libpwquality/libpwquality/releases/download/libpwquality-1.4.0/libpwquality-1.4.0.tar.bz2
Source0  : https://github.com/libpwquality/libpwquality/releases/download/libpwquality-1.4.0/libpwquality-1.4.0.tar.bz2
Summary  : A library for password generation and password quality checking
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: libpwquality-bin
Requires: libpwquality-python3
Requires: libpwquality-lib
Requires: libpwquality-locales
Requires: libpwquality-doc
Requires: libpwquality-python
BuildRequires : Linux-PAM-dev
BuildRequires : cracklib-dev
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
This is a library for password quality checks and generation
of random passwords that pass the checks.
This library uses the cracklib and cracklib dictionaries
to perform some of the checks.

%package bin
Summary: bin components for the libpwquality package.
Group: Binaries

%description bin
bin components for the libpwquality package.


%package dev
Summary: dev components for the libpwquality package.
Group: Development
Requires: libpwquality-lib
Requires: libpwquality-bin
Provides: libpwquality-devel

%description dev
dev components for the libpwquality package.


%package doc
Summary: doc components for the libpwquality package.
Group: Documentation

%description doc
doc components for the libpwquality package.


%package lib
Summary: lib components for the libpwquality package.
Group: Libraries

%description lib
lib components for the libpwquality package.


%package locales
Summary: locales components for the libpwquality package.
Group: Default

%description locales
locales components for the libpwquality package.


%package python
Summary: python components for the libpwquality package.
Group: Default
Requires: libpwquality-python3

%description python
python components for the libpwquality package.


%package python3
Summary: python3 components for the libpwquality package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libpwquality package.


%prep
%setup -q -n libpwquality-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517685267
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1517685267
rm -rf %{buildroot}
%make_install
%find_lang libpwquality

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pwmake
/usr/bin/pwscore

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libpwquality.so
/usr/lib64/pkgconfig/pwquality.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpwquality.so.1
/usr/lib64/libpwquality.so.1.0.2
/usr/lib64/security/pam_pwquality.so

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f libpwquality.lang
%defattr(-,root,root,-)

